### PR TITLE
IRust finally compiles using crossterm 0.12.1

### PR DESCRIPTION
**Pull request by quephird**
I could not simply do a `cargo install irust` nor clone the IRust repo and build it locally without encountering a bunch of errors all like this:

```Rust
   Compiling irust v0.7.20 (/Users/danielle/projects/IRust)
error[E0277]: `?` couldn't convert the error to `irust::irust_error::IRustError`
  --> src/irust.rs:87:60
   |
87 |         let _screen = crossterm::RawScreen::into_raw_mode()?;
   |                                                            ^ the trait `std::convert::From<crossterm_utils::error::ErrorKind>` is not implemented for `irust::irust_error::IRustError`
   |
   = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
   = help: the following implementations were found:
             <irust::irust_error::IRustError as std::convert::From<&irust::irust_error::IRustError>>
             <irust::irust_error::IRustError as std::convert::From<&mut irust::irust_error::IRustError>>
             <irust::irust_error::IRustError as std::convert::From<crossterm_utils::error::ErrorKind>>
             <irust::irust_error::IRustError as std::convert::From<std::io::Error>>
   = note: required by `std::convert::From::from`
```

Even trying 0.7.14 of IRust still led to the same errors. And so I assumed that there was something in the version of crossterm nominated in `Cargo.toml` that was perhaps not accounted for. Upping the version to 0.12.1 seemed to do the trick.

I'm hardly a Rust export, just a programming language enthusiast and so feel free to ignore this; I just wanted to capture what I did to get this to run.

### CODE REVIEW

**Comment by quephird** [comment]
GAH... I meant to open a PR on my own fork! Sorry!

**Comment by sigmaSd** [comment]
Hi @quephird thanks for notifying me about this! I'll check it out later feel free to open a pr in the mean time !

**Comment by sigmaSd** [comment]
Btw the error is probably when crossterm got refactored on that version they didnt rexport  the error type, I think they fixed that immediatly after

**Comment by sigmaSd** [comment]
@quephird I updated IRust to last crossterm version, the issue should be gone now
